version: '3'
services:
  correction:
    image: 'docker.pkg.github.com/alercebroker/tutorial_pipeline/correction:latest'
    volumes:
      - "../ztf_sample:/app/tests"
    network_mode: host
    environment:
      - DB_HOST=
      - DB_USER=
      - DB_PASSWORD=
      - DB_PORT=
      - DB_NAME=
      - CONSUMER_TOPICS=
      - CONSUMER_SERVER=
      - CONSUMER_GROUP_ID=
      - AVRO_PATH=
      - PRODUCER_TOPIC=
      - PRODUCER_SERVER=
      - ES_PREFIX=
      - ES_NETWORK_HOST=
      - ES_NETWORK_PORT=
      - LOGGING_DEBUG=True
      - N_PROCESS=1
