version: '3'
services:
  correction:
    image: 'docker.pkg.github.com/alercebroker/tutorial_pipeline/correction:latest'
    volumes:
      - "../ztf_sample:/app/tests"
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_PORT=5432
      - DB_NAME=test
      - CONSUMER_TOPICS=
      - CONSUMER_SERVER=
      - CONSUMER_GROUP_ID=
      - AVRO_PATH=/app/tests
      - PRODUCER_TOPIC=correction
      - PRODUCER_SERVER=localhost:9092
      - ES_PREFIX=tutorial
      - ES_NETWORK_HOST=localhost
      - ES_NETWORK_PORT=9200
      - LOGGING_DEBUG=True
      - N_PROCESS=1
