version: "3"
services:
  features:
    image: 'docker.pkg.github.com/alercebroker/tutorial_pipeline/features:latest'
    network_mode: host
    environment:
      - CONSUMER_TOPICS=
      - CONSUMER_SERVER=
      - CONSUMER_GROUP_ID=
      - PRODUCER_TOPIC=
      - PRODUCER_SERVER=
      - LOGGING_DEBUG=True
      - ES_PREFIX=
      - ES_NETWORK_HOST=
      - ES_NETWORK_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASSWORD=
      - DB_PORT=
      - DB_NAME=
